/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ReentrancyAuc,
  ReentrancyAucInterface,
} from "../../ReetrancyAttac.sol/ReentrancyAuc";

const _abi = [
  {
    inputs: [],
    name: "bid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "bidders",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061021b8061001f6000396000f3fe60806040526004361061003f5760003560e01c80631998aeef14610044578063590e1ae31461004e578063ce845d1d14610063578063fcc8f79314610084575b600080fd5b61004c6100b1565b005b34801561005a57600080fd5b5061004c6100d7565b34801561006f57600080fd5b50475b60405190815260200160405180910390f35b34801561009057600080fd5b5061007261009f36600461018e565b60006020819052908152604090205481565b33600090815260208190526040812080543492906100d09084906101be565b9091555050565b33600090815260208190526040902054801561018b57604051600090339083908381818185875af1925050503d806000811461012f576040519150601f19603f3d011682016040523d82523d6000602084013e610134565b606091505b50509050806101795760405162461bcd60e51b815260206004820152600d60248201526c1c99599d5b990819985a5b1959609a1b604482015260640160405180910390fd5b50336000908152602081905260408120555b50565b6000602082840312156101a057600080fd5b81356001600160a01b03811681146101b757600080fd5b9392505050565b808201808211156101df57634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220e1a917a022877f7ef78e3cb3cfe8f3e387b9774771aca37bf83ae0bf06076e0164736f6c63430008210033";

type ReentrancyAucConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyAucConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyAuc__factory extends ContractFactory {
  constructor(...args: ReentrancyAucConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReentrancyAuc & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrancyAuc__factory {
    return super.connect(runner) as ReentrancyAuc__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAucInterface {
    return new Interface(_abi) as ReentrancyAucInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyAuc {
    return new Contract(address, _abi, runner) as unknown as ReentrancyAuc;
  }
}
